services:
  react-app:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - flask-app
    develop:
      watch:
        - action: sync
          path: ./client/src
          target: /src/client
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
  flask-app:
    build: ./backend
    ports:
      - "5000:5000"
    links:
      - db
  db:
    image: mongo:latest
    hostname: importo_mongodb
    environment:
      - MONGO_INITDB_DATABASE=importo_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=db@!Rp2957
    volumes:
      - ./backend/db/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    ports:
      - 27017:27017
  